import Link from "next/link";

const labs = [
  { href: "/policy-lab", label: "01 · Policy boundary", title: "Hard limit → block → recovery", copy: "Run the real merchant quote and gateway policy engine, then show that only an authorized basket can reach Razorpay.", tag: "FINANCIAL AUTHORITY" },
  { href: "/tamper-lab", label: "02 · Amount integrity", title: "Client lies about price", copy: "Inject a deliberately false client-side total and watch the gateway ignore it in favor of the server-side merchant quote.", tag: "ANTI-TAMPERING" },
  { href: "/webhook-lab", label: "03 · Webhook safety", title: "Same event twice → one effect", copy: "Replay the same synthetic webhook identity twice and prove the persistent dedupe boundary rejects the second delivery.", tag: "IDEMPOTENCY" },
  { href: "http://localhost:3000/operations/persistence", label: "04 · Persistence", title: "Restart → state survives", copy: "Use the gateway persistence proof to show transactions, audit events and merchant revenue attribution survive a process restart.", tag: "POSTGRESQL" },
] as const;

export default function LabsPage() {
  return <main style={{ minHeight: "100vh", background: "#f7f7f3", color: "#171717", fontFamily: "Arial, sans-serif", padding: "36px 20px 72px" }}><div style={{ maxWidth: 1080, margin: "0 auto" }}>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 30 }}><Link href="/" style={{ textDecoration: "none", color: "#666", fontSize: 13 }}>← Buyer workspace</Link><span style={{ border: "1px solid #c8d8ce", background: "#eff6f1", color: "#1e5b3e", padding: "7px 10px", fontSize: 11, fontWeight: 700 }}>MANDATE · JUDGE LABS</span></div>
    <div style={{ borderTop: "2px solid #171717", paddingTop: 18 }}><div style={{ fontSize: 11, letterSpacing: ".12em", fontWeight: 700, color: "#777" }}>DEMO CONTROL ROOM</div><h1 style={{ fontSize: 56, lineHeight: 1, letterSpacing: "-.055em", margin: "12px 0 14px", maxWidth: 820 }}>Four proofs. One payment authority.</h1><p style={{ maxWidth: 760, color: "#666", lineHeight: 1.7, margin: 0 }}>Use these focused labs to demonstrate what separates MANDATE from a normal LLM checkout: spending authority, amount integrity, webhook idempotency and durable state.</p></div>
    <section style={{ marginTop: 34, display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 14 }}>{labs.map((lab) => <Link key={lab.href} href={lab.href} style={{ textDecoration: "none", color: "inherit", background: "white", border: "1px solid #dddcd7", padding: 24 }}><div style={{ fontSize: 10, color: "#777", letterSpacing: ".1em", fontWeight: 700 }}>{lab.label}</div><div style={{ fontSize: 29, letterSpacing: "-.035em", lineHeight: 1.15, marginTop: 12, fontWeight: 700 }}>{lab.title}</div><p style={{ color: "#666", fontSize: 13, lineHeight: 1.7, margin: "12px 0 18px" }}>{lab.copy}</p><span style={{ fontSize: 10, letterSpacing: ".08em", fontWeight: 700, color: "#1e5b3e" }}>{lab.tag} →</span></Link>)}</section>
    <section style={{ marginTop: 18, background: "#171717", color: "white", padding: 24 }}><div style={{ fontSize: 10, color: "#bcbcb8", letterSpacing: ".1em", fontWeight: 700 }}>DEMO SCRIPT</div><div style={{ marginTop: 12, fontSize: 18, lineHeight: 1.6, letterSpacing: "-.01em" }}>Start with the ₹5,000 policy block. Approve the basket. Raise the limit. Create the Test Mode order. Replay the webhook. Then restart the gateway and show that the same transaction and revenue attribution are still present.</div></section>
  </div></main>;
}
