import Link from "next/link";

const labs = [
  { href: "/golden-path", label: "00 · Golden path", title: "AI recommendation → payment", copy: "Run the canonical Track 01 scenario: model plan, merchant opportunity, explicit user approval, live quote, gateway policy and Razorpay Test Mode.", tag: "TRACK 01 CORE" },
  { href: "/capabilities", label: "01 · Agent discovery", title: "Merchant → capability handshake", copy: "Discover the live merchant agent, inspect its machine-readable capabilities, negotiate an actually usable protocol and see the payment rail it exposes.", tag: "AGENT INTEROPERABILITY" },
  { href: "/live-proof", label: "02 · Live proof", title: "Watch reconciliation settle", copy: "Auto-refresh the real transaction proof so webhook arrival, verification, merchant-order persistence and realized revenue can be observed without a manual reload.", tag: "REAL-TIME EVIDENCE" },
  { href: "http://localhost:3000/growth", label: "03 · Merchant growth", title: "Campaign → basket lift", copy: "Open the merchant growth command center to inspect campaign opportunities, potential lift and realized incremental revenue.", tag: "REVENUE GROWTH" },
  { href: "/demo", label: "04 · Demo readiness", title: "Are we ready to demo?", copy: "Run server-side health checks for the gateway, merchant, Razorpay test rail, agent manifest and persisted stores before presenting.", tag: "LIVE READINESS" },
  { href: "/proof", label: "05 · Unified proof", title: "One transaction → full chain", copy: "See buyer intent, policy authorization, Razorpay references, webhook evidence and realized merchant revenue together on one live screen.", tag: "END-TO-END" },
  { href: "/policy-lab", label: "06 · Policy boundary", title: "Hard limit → block → recovery", copy: "Run the real merchant quote and gateway policy engine, then show that only an authorized basket can reach Razorpay.", tag: "FINANCIAL AUTHORITY" },
  { href: "/tamper-lab", label: "07 · Amount integrity", title: "Client lies about price", copy: "Inject a deliberately false client-side total and watch the gateway ignore it in favor of the server-side merchant quote.", tag: "ANTI-TAMPERING" },
  { href: "/webhook-lab", label: "08 · Webhook safety", title: "Same event twice → one effect", copy: "Replay the same synthetic webhook identity twice and prove the persistent dedupe boundary rejects the second delivery.", tag: "IDEMPOTENCY" },
  { href: "http://localhost:3000/operations/persistence", label: "09 · Persistence", title: "Restart → state survives", copy: "Use the gateway persistence proof to show transactions, audit events and merchant revenue attribution survive a process restart.", tag: "POSTGRESQL" },
] as const;

export default function LabsPage() {
  return <main style={{ minHeight: "100vh", background: "#f7f7f3", color: "#171717", fontFamily: "Arial, sans-serif", padding: "36px 20px 72px" }}><div style={{ maxWidth: 1080, margin: "0 auto" }}>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 30 }}><Link href="/" style={{ textDecoration: "none", color: "#666", fontSize: 13 }}>← Buyer workspace</Link><span style={{ border: "1px solid #c8d8ce", background: "#eff6f1", color: "#1e5b3e", padding: "7px 10px", fontSize: 11, fontWeight: 700 }}>MANDATE · JUDGE LABS</span></div>
    <div style={{ borderTop: "2px solid #171717", paddingTop: 18 }}><div style={{ fontSize: 11, letterSpacing: ".12em", fontWeight: 700, color: "#777" }}>DEMO CONTROL ROOM</div><h1 style={{ fontSize: 56, lineHeight: 1, letterSpacing: "-.055em", margin: "12px 0 14px", maxWidth: 820 }}>One live transaction. Every proof.</h1><p style={{ maxWidth: 760, color: "#666", lineHeight: 1.7, margin: 0 }}>Start with the canonical golden path, then inspect agent discovery, live payment proof, merchant growth and the focused safety boundaries.</p></div>
    <section style={{ marginTop: 34, display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 14 }}>{labs.map((lab, index) => <Link key={lab.href} href={lab.href} style={{ textDecoration: "none", color: "inherit", background: "white", border: `1px solid ${index < 3 ? "#b8cdbf" : "#dddcd7"}`, padding: 24, gridColumn: index < 3 ? "1 / -1" : undefined }}><div style={{ fontSize: 10, color: "#777", letterSpacing: ".1em", fontWeight: 700 }}>{lab.label}</div><div style={{ fontSize: 29, letterSpacing: "-.035em", lineHeight: 1.15, marginTop: 12, fontWeight: 700 }}>{lab.title}</div><p style={{ color: "#666", fontSize: 13, lineHeight: 1.7, margin: "12px 0 18px", maxWidth: 820 }}>{lab.copy}</p><span style={{ fontSize: 10, letterSpacing: ".08em", fontWeight: 700, color: "#1e5b3e" }}>{lab.tag} →</span></Link>)}</section>
    <section style={{ marginTop: 18, background: "#171717", color: "white", padding: 24 }}><div style={{ fontSize: 10, color: "#bcbcb8", letterSpacing: ".1em", fontWeight: 700 }}>DEMO SCRIPT</div><div style={{ marginTop: 12, fontSize: 18, lineHeight: 1.6, letterSpacing: "-.01em" }}>Agent Discovery → Golden Path → show the merchant opportunity → approve the basket → authorize → open Razorpay Test Checkout → complete payment → switch to Live Proof and watch webhook/verification settle → open Merchant Growth to show realized uplift → run the policy/tamper/replay/persistence proofs.</div></section>
  </div></main>;
}
